### ISSUE TITLE
Bugs of evaluate spider 

### ISSUE THREAD

**Issue by YangHaolin0526** [RUCKBReasoning/TableLLM#12]
I encountered some problems when I was trying to evaluate spider datasets. The output accuracy is 0. (I used the inference result provided in your repository) 
![WechatIMG5685](https://github.com/user-attachments/assets/788bcc6a-08b4-491c-b1e3-d2fe76056d74)
When printing the result of the "run_code" variable in the "spider-eval/eval.py" file, I found that all the outputs are "None."
Maybe there is some error in the code eval.py? Can anyone help me to solve this problem?

**Comment by Kaka23333** [comment]
Thanks for pointing it out. We have fixed this error by adding `os.makedirs('tmp', exist_ok=True)`
