### ISSUE TITLE
Unexpected Results and 'None' Outputs with Inference Code and Evaluation

### ISSUE THREAD

**Issue by YangHaolin0526** [RUCKBReasoning/TableLLM#13]
When using the provided inference code and the TableLLM-7B model, the scores obtained are significantly lower than expected (as shown in the image). Upon further inspection, I discovered that more than half of the "assistant code" values are not Python code as anticipated. Instead, they appear to be explanatory answers. The inference results are quite different from the inferences provided in Github repository. This observation raises concerns about the correctness of the parameters used in the "inference_code.py" file, particularly the temperature = 0.8 and top_p = 0.95 settings. When printing the result of the "run_code" variable in the "wikisql-eval/eval.py" file, I found that more than half of the outputs are "None."
<img width="1095" alt="截屏2024-07-26 下午9 33 31" src="https://github.com/user-attachments/assets/8ed9d763-1b61-4e03-9054-3df567871fd5">
![WechatIMG5710](https://github.com/user-attachments/assets/fb1db703-768d-46cd-93b4-799dbb246749)

**Comment by Kaka23333** [comment]
Thanks for your comment. We may have uploaded the wrong version of the model. We have updated the [TableLLM-7B](https://huggingface.co/RUCKBReasoning/TableLLM-7b) model in Huggingface, and the new version achieves the corresponding performance in the paper.
