### ISSUE TITLE
Error occur when TLLM genereate response.

### ISSUE THREAD

**Issue by b5y** [RUCKBReasoning/TableLLM#15]
Hello!

Thank you for your work!

I followed guideline via [README](https://github.com/RUCKBReasoning/TableLLM?tab=readme-ov-file#deployment) how to deploy the model and did it on my local machine with 2 GPUs.

If I try to test on the default data, I am always getting `Error occur when TLLM genereate response.`.
Reading/writing from/into MongoDB works well.

See screenshots for more details.

One more thing to add: There is missing [`python-docx`](https://python-docx.readthedocs.io/en/latest/) library in [`requirements.txt`](https://github.com/RUCKBReasoning/TableLLM/blob/main/requirements.txt).

![Screenshot from 2024-08-07 13-11-27](https://github.com/user-attachments/assets/5044cc8f-7b4f-400f-93dc-7327ff48f5d3)
![Screenshot from 2024-08-07 13-11-09](https://github.com/user-attachments/assets/9a0202c7-b026-4c3a-87a4-f7ea57315f02)

Can you please comment on this and add missing python library in `requirements.txt` file?

**Comment by b5y** [comment]
Found a solution. The `model_url` should contain `generate` endpoint as [described in examples for vllm](https://docs.vllm.ai/en/latest/getting_started/examples/gradio_webserver.html).

**Comment by Kaka23333** [comment]
Thanks for pointing out this! We will update our README and deployment scripts.
