### ISSUE TITLE
请问这个模型对中文表格有支持吗

### ISSUE THREAD

**Issue by YuMingtao0503** [RUCKBReasoning/TableLLM#2]

**Comment by Kaka23333** [comment]
我们的基座模型和训练数据都为英文，但是经过测试，发现了模型有一定的中文能力。你可以在我们提供的[平台](http://36.103.203.47:27824/)上测试一下，看是否满足你的需求。

**Comment by YuMingtao0503** [comment]
> 我们的基础模型和训练数据都是英文的，但是经过测试，发现模型有一定的中文能力。您可以在我们提供的[平台](http://36.103.203.47:27824/)上测试一下，看看是否满足您的需求。

挺好的 对于较长的表格效果也可 但是具有多级索引的表格表现不好 这也是我目前想要实现的

**Comment by Kaka23333** [comment]
嗯嗯，感谢关注！后续我们将覆盖格式更多样的表格，并逐步完善除QA、表格操作之外的更加丰富的功能。

**Comment by ygc666666** [comment]
为什么你们提供的平台不能回答自己上传的表格

**Comment by lululubbb** [comment]
> 我们的基座模型和训练数据都为英文，但是经过测试，发现了模型有一定的中文能力。你可以在我们提供的[平台](http://36.103.203.47:27824/)上测试一下，看是否满足你的需求。

服务器没开吗，网页打不开，测试不了

**Comment by Kaka23333** [comment]
不好意思，目前部署的前端有bug，我们目前停止了服务，等调试完成后会重新开放

**Comment by charosen** [comment]
> 不好意思，目前部署的前端有bug，我们目前停止了服务，等调试完成后会重新开放

平台现在能访问了吗？有服务的代码吗？ @Kaka23333

**Comment by Kaka23333** [comment]
> > 不好意思，目前部署的前端有bug，我们目前停止了服务，等调试完成后会重新开放
> 
> 平台现在能访问了吗？有服务的代码吗？
不好意思，最近比较忙腾不出手来修复，平台预计在六月中旬重新上线。

**Comment by Kaka23333** [comment]
> > 不好意思，目前部署的前端有bug，我们目前停止了服务，等调试完成后会重新开放
> 
> 平台现在能访问了吗？有服务的代码吗？ @Kaka23333

不好意思隔了很久。我们更新了部署代码，包括前端与后端，参见deployment文件夹。我们同时重新上线了我们的平台。
