### ISSUE TITLE
请问一下如何部署这个模型呢？

### ISSUE THREAD

**Issue by cgq0816** [RUCKBReasoning/TableLLM#4]
如题

**Comment by Kaka23333** [comment]
感谢关注，我们的模型基于CodeLlama进行微调，可以使用所有支持CodeLlama的框架进行部署，例如目前主流的框架[vllm](https://github.com/vllm-project/vllm)。

**Comment by cgq0816** [comment]
> 感谢关注，我们的模型基于CodeLlama进行微调，可以使用所有支持CodeLlama的框架进行部署，例如目前主流的框架[vllm](https://github.com/vllm-project/vllm)。

你好，我通过vllm已经部署起来了，但是我如何验证模型推理是否正常呢？

使用了benchmark/wtq.jsonl中的第一条做推理，
https://github.com/TableLLM/TableLLM/blob/main/benchmark/wtq.jsonl
正确答案：
![image](https://github.com/TableLLM/TableLLM/assets/42534237/d1772d85-8169-42d8-83f1-f266d3459f4e)
模型推理结果：
![image](https://github.com/TableLLM/TableLLM/assets/42534237/68f2ebad-7dee-440e-a637-96073b1ad45a)
发现推理的答案和正确答案不一致

**Comment by Kaka23333** [comment]
您好，wtq是一个相对较难的benchmark，我们的7B和13B模型在wtq上的准确率分别为58.8%和62.4%，对于单个数据点是有可能出现回答错误的情况的。如果您想验证模型的输出是否正常，可以尝试复现我们的实验结果，我们提供了推理脚本，可参考[readme](https://github.com/TableLLM/TableLLM?tab=readme-ov-file#inference)中的相关部分。

**Comment by lululubbb** [comment]
您好我想问一下您是如何部署的呢，可以请教一下吗，纯小白

**Comment by Kaka23333** [comment]
> 您好我想问一下您是如何部署的呢，可以请教一下吗，纯小白

你好，我们更新了部署代码，参见deployment文件夹

**Comment by lululubbb** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
