### ISSUE TITLE
There is a problem with the code logic of eval

### ISSUE THREAD

**Issue by renllll** [RUCKBReasoning/TableLLM#7]
There is a problem with the eval code in this experiment. Many times, if the logic of the variable extraction part of the code is incorrect, it will lead to the fact that the code is obviously correct, but the variables cannot be extracted. When I used llama3 to reproduce your experiment, if I used your eval code, the accuracy rate was only 17, and I changed the method to determine whether all the correct results are in the printed output. If so, it is correct. This When, the accuracy rate is 70.12%

**Comment by renllll** [comment]
Your tablellm-13b has a score of 83.79 on my review methodology.

**Comment by Kaka23333** [comment]
Thanks for pointing out this problem. Is it possible to open a pull request for your modified review methodology?
